version: '2.0'
services:
  jenkins:
    image: pablords/jenkins-as-code:1.0.3
    build: .
    container_name: jenkins
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./src/main/init.groovy.d:/usr/share/jenkins/ref/init.groovy.d
      - ./src/main/properties:/usr/share/jenkins/ref/properties
      - ./src/main/jobs:/usr/share/jenkins/ref/config/initials
    environment:
      - KUBERNETES_SERVER_URL=https://192.168.50.10:6443
      - JENKINS_SERVER_URL=http://192.168.50.10:8080
      - JENKINS_TUNNEL_URL=192.168.50.10:50000
      - SONARQUBE_URL=http://dev-testdevops.ddns.net:9000
      - VAULT_URL=http://dev-testdevops.ddns.net:8083
      - VAULT_TOKEN_ADMIN=




