version: '3.3'

services:
  jenkins:
    image: jenkins-dev
    build: .
    container_name: jenkins
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./data:/var/jenkins_home
