version: '3.3'

services:
  jenkins:
    image: pablords/jenkins-as-code:1.0.1
    build: .
    container_name: jenkins
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./data:/var/jenkins_home
    environment:
      - KUBERNETES_SERVER_URL=https://192.168.50.10:6443
      - JENKINS_SERVER_URL=http://192.168.50.10:8080
      - JENKINS_TUNNEL_URL=192.168.50.10:50000
