apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: devops
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: pablords/jenkins-as-code:1.0.3
          imagePullPolicy: Always
          resources:
          ports:
            - name: http-port
              containerPort: 8080
            - name: jnlp-port
              containerPort: 50000
          env:
            - name: KUBERNETES_SERVER_URL
              value: ""
            - name: SONARQUBE_URL
              value: "http://devops-dev.ddns.net:9000"
            - name: VAULT_URL
              value: "http://devops-dev.ddns.net:8083"
            - name: JENKINS_SERVER_URL
              value: http://jenkins.devops.svc.cluster.local:8080
            - name: JENKINS_TUNNEL_URL
              value: jenkins-jnlp.devops.svc.cluster.local:50000
            - name: VAULT_TOKEN_ADMIN
              valueFrom:
                secretKeyRef:
                  name: vault-root-credential
                  key: secret
          volumeMounts:
            - name: jenkins-vol
              mountPath: /var/jenkins_home
      volumes:
        - name: jenkins-vol
          emptyDir: {}
      #volumes:
      #  - name: jenkins-vol
      #    persistentVolumeClaim:
      #      claimName: jenkins-pvc
      #securityContext:
      #  fsGroup: 1000
      #  runAsUser: 0
