apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistentVolume.name }}
  namespace: {{ .Values.metadata.namespace }}
  annotations:
    pv.beta.kubernetes.io/gid: {{ .Values.persistentVolume.annotations }}
  labels:
    type: {{ .Values.persistentVolume.labels.type }}
spec:
  storageClassName: {{ .Values.persistentVolume.storageClassName }}
  capacity:
    storage: {{ .Values.persistentVolume.capacity.storage }}
  accessModes:
    - {{ .Values.persistentVolume.accessModes }}
  hostPath:
    path: {{ .Values.persistentVolume.hostPath.path }}