apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistentVolumeClaim.name }}
  namespace:  {{ .Values.metadata.namespace }}
spec:
  storageClassName:  {{ .Values.persistentVolumeClaim.storageClassName }}
  accessModes:
    -  {{ .Values.persistentVolumeClaim.accessModes }}
  resources:
    requests:
      storage:  {{ .Values.persistentVolumeClaim.storage }}