apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.metadata.name }}
  namespace: {{ .Values.metadata.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.rolebinding.default.roleRef.name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.rolebinding.default.subjects.name }}
