apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.http.name }}
  namespace: {{ .Values.metadata.namespace }}
  labels:
    app: {{ .Values.metadata.labels.app }}
spec:
  type: {{ .Values.service.http.type }}
  ports:
    - port: {{ .Values.service.http.port }}
      targetPort: {{ .Values.service.http.targetPort }}
      #nodePort: {{ .Values.service.http.nodePort }}
  selector:
    app: {{ .Values.service.http.selector.app }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.jnlp.name }}
  namespace: {{ .Values.metadata.namespace }}
  labels:
    app: {{ .Values.metadata.labels.app }}
spec:
  type: {{ .Values.service.jnlp.type }}
  ports:
    - port: {{ .Values.service.jnlp.port }}
      targetPort: {{ .Values.service.jnlp.targetPort }}
      #nodePort: {{ .Values.service.jnlp.nodePort }}
  selector:
    app: {{ .Values.service.jnlp.selector.app }}